version: '3.7'

services:

  gobeventproducer:
    env_file: ./.env
    build: src
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      GOB_SHARED_DIR: /app/shared
      GOB_EVENTPRODUCER_DATABASE_HOST: eventproducer_database
      GOB_EVENTPRODUCER_DATABASE_PORT: 5432
      GOB_EVENTPRODUCER_DATABASE_USER: gob_eventproducer
      GOB_EVENTPRODUCER_DATABASE_PASSWORD: insecure
      GOB_EVENTPRODUCER_DATABASE: gob_eventproducer
      GOB_DATABASE_PORT_OVERRIDE: 5432
      GOB_DATABASE_HOST_OVERRIDE: database

    volumes:
      - gob-volume:/app/shared
      - ./src/gobeventproducer:/app/gobeventproducer
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config

  eventproducer_database:
    image: amsterdam/postgres11
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob_eventproducer
      POSTGRES_USER: gob_eventproducer
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    shm_size: '1gb'

volumes:
  gob-volume:
    external: true

networks:
  default:
    name: gob-network
    external: true
