version: '3.0'

services:

  gobkafkaproducer:
    build: src
    container_name: gobkafkaproducer
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      GOB_SHARED_DIR: /app/shared
    volumes:
      - gob-volume:/app/shared

networks:
  default:
    external:
      name: gob-network
