"""initial

Revision ID: 1f8862ab65bb
Revises: 
Create Date: 2020-12-17 16:13:57.910919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8862ab65bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_sent_events',
    sa.Column('catalogue', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('last_event', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('catalogue', 'collection')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_sent_events')
    # ### end Alembic commands ###
